-   id: poetry-check
    name: poetry check
    entry: poetry check
    pass_filenames: false
    language: python
    require_serial: false
    additional_dependencies: []
    files: pyproject\.toml

-   id: poetry-lock
    name: poetry lock
    entry: python -m poetry_lock_check check-lock
    pass_filenames: false
    language: python
    require_serial: false
    additional_dependencies: []
    files: pyproject\.toml|poetry\.lock